[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.63"

[[constraint]]
  name = "github.com/pilosa/go-pilosa"
  branch = "master"

[[constraint]]
  name = "github.com/pilosa/pilosa"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
