densityscale = 2097152
version = "1.0"
[indexes.users]
columns = 100
fields = [
# age = { type = "int", min = 10, max = 120 }
# { name = "income", type = "int", min = 0, max = 640000, density = 1.0 },
{ name = "numbers", type = "set", max = 2, density = 0.01, },
{ name = "numbers", type = "set", chance = 0.05, density = 1.0, },
]
[[workloads]]
name = "sample"
threadCount = 1
tasks = [
# { index = "users", field = "income", },
{ index = "users", field = "numbers", columnOrder = "stride", stride = 3 },
]
# tasks = [
# { index = "users", field = "income", columnOrder = "permute" },
# ]
