version = "1.0"
fast = true
[indexes.users]
columns = 1000000000
fields = [
{name = "numbers", type = "set", min=0, max=100000, zipfA=3.0 },
]
[[workloads]]
name = "sample"
threadCount = 1
tasks = [
{ index = "users", field = "numbers", columnOrder = "stride", stride = 3, dimensionOrder="row" },
]
