version = "1.0"
[indexes.users]
columns = 1000000000
fields = [
{name = "numbers", type = "set", min=0, max=10000, zipfA=1.0, fastSparse = true, density = 0.1 },
]
[[workloads]]
name = "sample"
threadCount = 1
tasks = [
{ index = "users", field = "numbers", columnOrder = "stride", stride = 3, dimensionOrder="row" },
]
