densityscale = 2097152
version = "1.0"
[indexes.users]
columns = 100000
threadCount = 4
[indexes.users.fields]
# age = { type = "BSI", min = 10, max = 120 }
income = { type = "bsi", min = 0, max = 640000, density = 1.0 }
numbers = { type = "set", max = 100, density = 1.0, valueRule = "zipf", zipfV = 2.0, zipfS = 1.01 }
[[workloads]]
name = "sample"
[[workloads.batches]]
description = "initial"
tasks = [
{ index = "users", field = "income" },
{ index = "users", field = "numbers" },
]
[[workloads.batches]]
description = "repopulate"
tasks = [
{ index = "users", field = "income", columns = 10000, columnOrder = "permute" },
]
