densityscale = 2097152
version = "1.0"
[[indexes]]
name = "users"
columns = 100000
threadCount = 4
[indexes.fields]
# age = { type = "BSI", min = 10, max = 120 }
income = { type = "bsi", min = 0, max = 640000, columns = 10000, columnOrder = "stride", stride = 5 }
numbers = { type = "set", max = 100, density = 1.0, valueRule = "zipf", zipfV = 2.0, zipfS = 1.01 }

[[indexes]]
name = "events"
columns = 100000
[indexes.fields]
user = { type = "bsi", sourceindex = "users", dimensionOrder = "row" }
