densityscale = 2097152
version = "1.0"
[indexes.students_ts]
columns = 10000000
fields = [
{ name = "age", type = "bsi", max = 100, min=14, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
]
[[workloads]]
name = "ingest"
threadCount = 6
batchSize = 1048576
useRoaring = true
[[workloads.batches]]
[[workloads.batches]]
description = "import16"
tasks = [{ index = "students_ts", field = "age", seed = 1 }]
