# int ingest/update for 16/32/63-bit values.
# things act weird if the actual range exceeds 2^63
densityscale = 2097152
version = "1.0"
[indexes.inttest]
columns = 1000000
fields = [
{ name = "int16", type = "int", max = 65535, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
{ name = "int32", type = "int", max = 4294967295, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
{ name = "int63", type = "int", max = 9223372036854775807, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
]
[[workloads]]
name = "Int initial import"
[[workloads.batches]]
description = "import16"
tasks = [{ index = "inttest", field = "int16", seed = 1 }]
[[workloads.batches]]
description = "import32"
tasks = [{ index = "inttest", field = "int32", seed = 2 }]
[[workloads.batches]]
description = "import63"
tasks = [{ index = "inttest", field = "int63", seed = 3 }]
[[workloads]]
name = "Int updates"
[[workloads.batches]]
description = "import16"
tasks = [{ index = "inttest", field = "int16", seed = 4, columns = 1000, columnOrder = "permute" }]
[[workloads.batches]]
description = "import32"
tasks = [{ index = "inttest", field = "int32", seed = 5, columns = 1000, columnOrder = "permute" }]
[[workloads.batches]]
description = "import63"
tasks = [{ index = "inttest", field = "int63", seed = 6, columns = 1000, columnOrder = "permute" }]
