# BSI ingest/update for 16/32/63-bit values.
# things act weird if the actual range exceeds 2^63
densityscale = 2097152
version = "1.0"
[indexes.bsitest]
columns = 1000000
fields = [
{ name = "bsi16", type = "bsi", max = 65535, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
{ name = "bsi32", type = "bsi", max = 4294967295, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
{ name = "bsi63", type = "bsi", max = 9223372036854775807, density = 0.99, valueRule = "zipf", zipfV = 3.0, zipfS = 1.1 },
]
[[workloads]]
name = "BSI initial import"
[[workloads.batches]]
description = "import16"
tasks = [{ index = "bsitest", field = "bsi16", seed = 1 }]
[[workloads.batches]]
description = "import32"
tasks = [{ index = "bsitest", field = "bsi32", seed = 2 }]
[[workloads.batches]]
description = "import63"
tasks = [{ index = "bsitest", field = "bsi63", seed = 3 }]
[[workloads]]
name = "BSI updates"
[[workloads.batches]]
description = "import16"
tasks = [{ index = "bsitest", field = "bsi16", seed = 4, columns = 1000, columnOrder = "permute" }]
[[workloads.batches]]
description = "import32"
tasks = [{ index = "bsitest", field = "bsi32", seed = 5, columns = 1000, columnOrder = "permute" }]
[[workloads.batches]]
description = "import63"
tasks = [{ index = "bsitest", field = "bsi63", seed = 6, columns = 1000, columnOrder = "permute" }]
