densityscale = 2097152
version = "1.0"
[indexes.players]
columns = 5000000000
fields = [
{ name = "timey", type = "set", max = 10, density = 0.03, },
]
[[workloads]]
name = "ingest"
threadCount = 1
[[workloads.batches]]
description = "initial"
tasks = [
{ index = "players", field = "timey", columnOrder = "permute", columns = 500 },
]
