densityscale = 2097152
version = "1.0"
[indexes.users]
columns = 100000000
fields = [
{ name = "timey", type = "time", max = 100, density = 0.10, valueRule = "zipf", quantum = "YMDH" },
]
[[workloads]]
name = "ingest"
threadCount = 4
batchSize = 1048576
useRoaring = true
tasks = [
    { index = "users", field = "timey", stamp = "increasing", stampRange = "7560h", columns = 100000000 },
]
