densityscale = 2097152
version = "1.0"
[indexes.users]
columns = 5000000000
fields = [
{ name = "timey", type = "time", max = 10, density = 0.03, },
]
[[workloads]]
name = "ingest"
threadCount = 1
[[workloads.batches]]
description = "initial"
tasks = [
{ index = "users", field = "timey", columnOrder = "permute", stamp = "increasing", stampRange = "216h", columns = 500 },
]
