densityscale = 2097152
version = "1.0"
[indexes.students_ts]
columns = 10000000
fields = [
{ name = "gender", type = "mutex", max = 3, density = 0.9, valueRule = "linear", cache = "lru" },
{ name = "school", type = "set", max = 3000, density = 0.10, valueRule = "zipf" , cache = "lru" },
{ name = "timestamp", type = "time", max=1, density = 1.0, valueRule="linear" },
#{ name = "client_mac", type="set", max=10000000, density=0.001, valueRule="zipf"},
{ name = "zone", type="set", max=300, density=0.1, valueRule="zipf", cache = "lru" },
{ name = "age", type="bsi", max=100, min=14, valueRule="zipf"},
{ name = "on_campus", type="mutex", max=2, density=0.9, valueRule="zipf", cache = "lru" },
{ name = "athlete", type="mutex", max=2, density=1.0, valueRule="linear", cache = "lru" },
{ name = "gpa", type="bsi", max=400, valueRule="zipf"},
]
[[workloads]]
name = "ingest"
threadCount = 6
batchSize = 1048576
useRoaring = true
[[workloads.batches]]
description = "initial"
tasks = [
{ index = "students_ts", field = "gender"},
{ index = "students_ts", field = "school"},
{ index = "students_ts", field = "timestamp"},
#{ index = "students_ts", field = "client_mac"},
{ index = "students_ts", field = "zone"},
{ index = "students_ts", field = "age"},
{ index = "students_ts", field = "on_campus"},
{ index = "students_ts", field = "gpa"},
]
