densityscale = 2097152
version = "1.0"
[indexes.students_ts]
columns = 10000
fields = [
{ name = "gender", type = "mutex", max = 3, density = 0.9, valueRule = "linear", cache = "lru" },
{ name = "school", type = "set", max = 400, density = 0.10, valueRule = "zipf" , cache = "lru" },
{ name = "timestamp", type = "time", max=1, density = 1.0, valueRule="zipf", quantum="YMDH" },
#{ name = "client_mac", type="set", max=10000000, density=0.001, valueRule="zipf"},
{ name = "zone", type="set", max=300, density=0.1, valueRule="zipf", cache = "lru" },
{ name = "age", type="int", max=100, min=14, density=0.99, valueRule="zipf", zipfV = 3.0, zipfS = 1.1 },
{ name = "on_campus", type="mutex", max=2, density=0.9, valueRule="zipf", cache = "lru", zipfS = 1.1, zipfV = 3.0 },
{ name = "athlete", type="mutex", max=2, density=1.0, valueRule="linear", cache = "lru" },
{ name = "gpa", type="int", max=400, min=0, density=0.99, valueRule="zipf", zipfV = 3.0, zipfS = 1.1 },
]
[[workloads]]
name = "ingest"
threadCount = 6
batchSize = 1048576
useRoaring = true
[[workloads.batches]]
description = "initial"
tasks = [
{ index = "students_ts", field = "gender"},
{ index = "students_ts", field = "school"},
{ index = "students_ts", field = "timestamp", stamp = "increasing", stampStart = "2019-01-01T00:00:00Z", stampRange = "240h" },
#{ index = "students_ts", field = "client_mac"},
{ index = "students_ts", field = "zone"},
{ index = "students_ts", field = "age", seed = 1},
{ index = "students_ts", field = "on_campus"},
{ index = "students_ts", field = "gpa", seed = 2},
]
